name: Publish @__dirname/pixiv-web-api

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - packages/pixiv-web-api/package.json

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
    publish-npm:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
                  registry-url: "https://registry.npmjs.org"
            - uses: pnpm/action-setup@v4

            - name: Build package
              run: |
                  mv ./README.md ./packages/pixiv-web-api/
                  pnpm install
                  pnpm run build:api

            - name: Publishing on NPM
              uses: JS-DevTools/npm-publish@v4
              with:
                  token: ${{secrets.NPM_TOKEN}}
                  package: ./packages/pixiv-web-api
                  access: public
                  provenance: true
